"""Fixed scoring tests. Do not edit this file, and do not let the agent edit it.

Five scenarios, in the order the task describes them:
  1. the behaviour that already works, which must keep working
  2. swapped column order
  3. a missing email column
  4. empty values
  5. non-ASCII values
"""

import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from import_contacts import MissingColumnError, import_contacts  # noqa: E402


def write_csv(text):
    handle = tempfile.NamedTemporaryFile(
        "w", suffix=".csv", delete=False, encoding="utf-8", newline=""
    )
    handle.write(text)
    handle.close()
    return handle.name


class ImportContactsTest(unittest.TestCase):
    def test_1_documented_order_still_works(self):
        path = write_csv("name,email\nAda,ada@example.com\n")
        self.assertEqual(
            import_contacts(path), [{"name": "Ada", "email": "ada@example.com"}]
        )

    def test_2_columns_may_be_swapped(self):
        path = write_csv("email,name\nada@example.com,Ada\n")
        self.assertEqual(
            import_contacts(path), [{"name": "Ada", "email": "ada@example.com"}]
        )

    def test_3_missing_email_column_is_named(self):
        path = write_csv("name\nAda\n")
        with self.assertRaises(MissingColumnError) as caught:
            import_contacts(path)
        self.assertIn("email", str(caught.exception))

    def test_4_empty_values_are_kept(self):
        path = write_csv("name,email\nAda,\n")
        self.assertEqual(import_contacts(path), [{"name": "Ada", "email": ""}])

    def test_5_non_ascii_values_survive(self):
        path = write_csv("name,email\n高小明,高@example.com\n")
        self.assertEqual(
            import_contacts(path), [{"name": "高小明", "email": "高@example.com"}]
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
